### ISSUE TITLE
feat: status endpoint

### ISSUE THREAD

**Issue by castdrian** [movie-web/backend#4]
it would be nice to have a status endpoint that can be pinged and also one that returns the provider status as given in the pinned issue, both of these would allow a quite detailed `/status` command for mw-bot to be able to easily check if any connectivity or provider issues are currently known

**Comment by mrjvs** [comment]
we will have a healthcheck endpoint, which will return information on if the backend is healthy.
This is good practice for containerization and general infra maintenance.
However I don't think its in scope of the backend to return provider information.

the backend doesn't touch providers, its not a concept that known to it. Only the frontend knowns about providers, the backend is and should be just a minimal glorified database.

PS: All issues for all repos are now in the main repository. issues tab of singular repos aren't used.
